channels:
  - conda-forge
dependencies:
  - python=3.12
  - fastapi
  - uvicorn
  - sqlalchemy
  - zstandard
  - zstd
  - jinja2
  - tabulate
  - importlib_resources
  - click
  - libblas=*=*openblas
  # linux-only
  - _openmp_mutex=*=*_llvm